server:
  port: 8080
  servlet:
    context-path: /wxgsc
#mysql
spring:
  datasource:
    url: jdbc:mysql://47.115.22.141:3306/crh-gsc?characterEncoding=utf8&useSSL=false
    username: root
    password: chenrenhao
    driverClassName: com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapperLocations: classpath:com/crh/wxbase/gsc/mapper/*.xml
  typeAliasesPackage: com.crh.wxbase.gsc.entity
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true #驼峰下划线转换
      logic-delete-value: 0 #逻辑删除配置
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
