server:
  port: 9081
  servlet:
    context-path: /wxgsc

spring:
  datasource:
    url: jdbc:mysql://47.115.22.141:3306/crh-gsc?characterEncoding=utf8&useSSL=false
    username: root
    password: chenrenhao
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 47.115.22.141
    port: 6379
    database: 0
    password: chenrenhao
    timeout: 5000
    lettuce:
      pool:
        max-active: 32 # 最大活跃连接数 默认8
        max-idle: 8 # 最大空闲连接数 默认8
        min-idle: 5 # 最小空闲连接数 默认0

#mybatis-plus
mybatis-plus:
  mapperLocations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.crh.wxbase.*.entity
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true #驼峰下划线转换
      logic-delete-value: 0 #逻辑删除配置
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false

wechat:
  loginUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxad5128056ba6d81f
  secret: b054c08e8741b970c798310651ae722c
  grantType: authorization_code
